"""
Lookup tables for data on Chao

Data taken from: https://chao.tehfusion.co.uk/chao-hacking/
"""

# TODO : Checking function for this data.

DATA_TYPE_LENGTHS = {
    "Byte": 1,
    "Signed byte": 1,
    "Short": 2,
    "Int": 4,
    "Float": 4,
}

CHAO_OFFSETS = [
    {"Attribute": "Name", "Offset": 18, "Data type": "Byte", "Lookup": None},
    {"Attribute": "Swim stat bar", "Offset": 32, "Data type": "Byte", "Lookup": None},
    {"Attribute": "Fly stat bar", "Offset": 33, "Data type": "Byte", "Lookup": None},
    {"Attribute": "Run stat bar", "Offset": 34, "Data type": "Byte", "Lookup": None},
    {"Attribute": "Power stat bar", "Offset": 35, "Data type": "Byte", "Lookup": None},
    {
        "Attribute": "Stamina stat bar",
        "Offset": 36,
        "Data type": "Byte",
        "Lookup": None,
    },
    {"Attribute": "Luck stat bar", "Offset": 37, "Data type": "Byte", "Lookup": None},
    {
        "Attribute": "Intelligence stat bar",
        "Offset": 38,
        "Data type": "Byte",
        "Lookup": None,
    },
    {
        "Attribute": "Unknown stat bar",
        "Offset": 39,
        "Data type": "Byte",
        "Lookup": None,
    },
    {
        "Attribute": "Swim stat grade",
        "Offset": 40,
        "Data type": "Byte",
        "Lookup": "Grade",
    },
    {
        "Attribute": "Fly stat grade",
        "Offset": 41,
        "Data type": "Byte",
        "Lookup": "Grade",
    },
    {
        "Attribute": "Run stat grade",
        "Offset": 42,
        "Data type": "Byte",
        "Lookup": "Grade",
    },
    {
        "Attribute": "Power stat grade",
        "Offset": 43,
        "Data type": "Byte",
        "Lookup": "Grade",
    },
    {
        "Attribute": "Stamina stat grade",
        "Offset": 44,
        "Data type": "Byte",
        "Lookup": "Grade",
    },
    {"Attribute": "Luck stat grade", "Offset": 45, "Data type": "Byte", "Lookup": None},
    {
        "Attribute": "Intelligence stat grade",
        "Offset": 46,
        "Data type": "Byte",
        "Lookup": None,
    },
    {
        "Attribute": "Unknown stat grade",
        "Offset": 47,
        "Data type": "Byte",
        "Lookup": None,
    },
    {"Attribute": "Swim stat level", "Offset": 48, "Data type": "Byte", "Lookup": None},
    {"Attribute": "Fly stat level", "Offset": 49, "Data type": "Byte", "Lookup": None},
    {"Attribute": "Run stat level", "Offset": 50, "Data type": "Byte", "Lookup": None},
    {
        "Attribute": "Power stat level",
        "Offset": 51,
        "Data type": "Byte",
        "Lookup": None,
    },
    {
        "Attribute": "Stamina stat level",
        "Offset": 52,
        "Data type": "Byte",
        "Lookup": None,
    },
    {"Attribute": "Luck stat level", "Offset": 53, "Data type": "Byte", "Lookup": None},
    {
        "Attribute": "Intelligence stat level",
        "Offset": 54,
        "Data type": "Byte",
        "Lookup": None,
    },
    {
        "Attribute": "Unknown stat level",
        "Offset": 55,
        "Data type": "Byte",
        "Lookup": None,
    },
    {
        "Attribute": "Swim stat points",
        "Offset": 56,
        "Data type": "Short",
        "Lookup": None,
    },
    {
        "Attribute": "Fly stat points",
        "Offset": 58,
        "Data type": "Short",
        "Lookup": None,
    },
    {
        "Attribute": "Run stat points",
        "Offset": 60,
        "Data type": "Short",
        "Lookup": None,
    },
    {
        "Attribute": "Power stat points",
        "Offset": 62,
        "Data type": "Short",
        "Lookup": None,
    },
    {
        "Attribute": "Stamina stat points",
        "Offset": 64,
        "Data type": "Short",
        "Lookup": None,
    },
    {
        "Attribute": "Luck stat points",
        "Offset": 66,
        "Data type": "Short",
        "Lookup": None,
    },
    {
        "Attribute": "Intelligence stat points",
        "Offset": 68,
        "Data type": "Short",
        "Lookup": None,
    },
    {
        "Attribute": "Unknown stat points",
        "Offset": 70,
        "Data type": "Short",
        "Lookup": None,
    },
    {
        "Attribute": "Chao type",
        "Offset": 128,
        "Data type": "Byte",
        "Lookup": "ChaoType",
    },
    {
        "Attribute": "Chao garden",
        "Offset": 129,
        "Data type": "Byte",
        "Lookup": "SA2BChaoGarden",
    },
    {
        "Attribute": "Happiness",
        "Offset": 130,
        "Data type": "Signed byte",
        "Lookup": None,
    },
    {
        "Attribute": "Remaining lifespan 1",
        "Offset": 138,
        "Data type": "Short",
        "Lookup": None,
    },
    {
        "Attribute": "Remaining lifespan 2",
        "Offset": 140,
        "Data type": "Short",
        "Lookup": None,
    },
    {
        "Attribute": "Reincarnations",
        "Offset": 142,
        "Data type": "Short",
        "Lookup": None,
    },
    {
        "Attribute": "Run ↔ Power transformation",
        "Offset": 168,
        "Data type": "Float",
        "Lookup": None,
    },
    {
        "Attribute": "Swim ↔ Fly transformation",
        "Offset": 172,
        "Data type": "Float",
        "Lookup": None,
    },
    {"Attribute": "Alignment", "Offset": 176, "Data type": "Float", "Lookup": None},
    {
        "Attribute": "Transformation magnitude",
        "Offset": 192,
        "Data type": "Float",
        "Lookup": None,
    },
    {"Attribute": "Eyes", "Offset": 209, "Data type": "Byte", "Lookup": "Eyes"},
    {"Attribute": "Mouth", "Offset": 210, "Data type": "Byte", "Lookup": "Mouth"},
    {
        "Attribute": "Emotiball",
        "Offset": 211,
        "Data type": "Byte",
        "Lookup": "Emotiball",
    },
    {"Attribute": "Hat", "Offset": 213, "Data type": "Byte", "Lookup": "SA2BHat"},
    {
        "Attribute": "Hidden feet flag",
        "Offset": 214,
        "Data type": "Boolean",
        "Lookup": None,
    },
    {"Attribute": "Medal", "Offset": 215, "Data type": "Byte", "Lookup": "Medal"},
    {"Attribute": "Colour", "Offset": 216, "Data type": "Byte", "Lookup": "SA2BColour"},
    {
        "Attribute": "Mono-tone flag",
        "Offset": 217,
        "Data type": "Boolean",
        "Lookup": None,
    },
    {
        "Attribute": "Texture",
        "Offset": 218,
        "Data type": "Byte",
        "Lookup": "SA2BTexture",
    },
    {"Attribute": "Shiny flag", "Offset": 219, "Data type": "Boolean", "Lookup": None},
    {
        "Attribute": "Egg colour",
        "Offset": 220,
        "Data type": "Byte",
        "Lookup": "SA2BEggColour",
    },
    {
        "Attribute": "Body type",
        "Offset": 221,
        "Data type": "Byte",
        "Lookup": "SA2BBodyType",
    },
    {
        "Attribute": "Body type animal",
        "Offset": 222,
        "Data type": "Byte",
        "Lookup": "SA2BAnimal",
    },
    {
        "Attribute": "SA2B animal behaviours",
        "Offset": 280,
        "Data type": "Short",
        "Lookup": "SA2BAnimalFlags",
    },
    {
        "Attribute": "SA2B arms part",
        "Offset": 284,
        "Data type": "Byte",
        "Lookup": "SA2BAnimal",
    },
    {
        "Attribute": "SA2B ears part",
        "Offset": 285,
        "Data type": "Byte",
        "Lookup": "SA2BAnimal",
    },
    {
        "Attribute": "SA2B forehead part",
        "Offset": 286,
        "Data type": "Byte",
        "Lookup": "SA2BAnimal",
    },
    {
        "Attribute": "SA2B horns part",
        "Offset": 287,
        "Data type": "Byte",
        "Lookup": "SA2BAnimal",
    },
    {
        "Attribute": "SA2B legs part",
        "Offset": 288,
        "Data type": "Byte",
        "Lookup": "SA2BAnimal",
    },
    {
        "Attribute": "SA2B tail part",
        "Offset": 289,
        "Data type": "Byte",
        "Lookup": "SA2BAnimal",
    },
    {
        "Attribute": "SA2B wings part",
        "Offset": 290,
        "Data type": "Byte",
        "Lookup": "SA2BAnimal",
    },
    {
        "Attribute": "SA2B face part",
        "Offset": 291,
        "Data type": "Byte",
        "Lookup": "SA2BAnimal",
    },
    {"Attribute": "Sleepiness", "Offset": 292, "Data type": "Short", "Lookup": None},
    {"Attribute": "Joy", "Offset": 300, "Data type": "Byte", "Lookup": None},
    {"Attribute": "Urge to cry", "Offset": 302, "Data type": "Byte", "Lookup": None},
    {"Attribute": "Fear", "Offset": 303, "Data type": "Byte", "Lookup": None},
    {"Attribute": "Dizziness", "Offset": 305, "Data type": "Byte", "Lookup": None},
    {"Attribute": "Tiredness", "Offset": 310, "Data type": "Short", "Lookup": None},
    {"Attribute": "Hunger", "Offset": 312, "Data type": "Short", "Lookup": None},
    {
        "Attribute": "Desire to mate",
        "Offset": 314,
        "Data type": "Short",
        "Lookup": None,
    },
    {"Attribute": "Boredom", "Offset": 316, "Data type": "Short", "Lookup": None},
    {"Attribute": "Energy", "Offset": 328, "Data type": "Short", "Lookup": None},
    {
        "Attribute": "Normal ↔ Curious personality",
        "Offset": 330,
        "Data type": "Signed byte",
        "Lookup": None,
    },
    {
        "Attribute": "Cry Baby ↔ Energetic personality",
        "Offset": 332,
        "Data type": "Signed byte",
        "Lookup": None,
    },
    {
        "Attribute": "Naive ↔ Normal personality",
        "Offset": 333,
        "Data type": "Signed byte",
        "Lookup": None,
    },
    {
        "Attribute": "Normal ↔ Big Eater personality",
        "Offset": 336,
        "Data type": "Signed byte",
        "Lookup": None,
    },
    {
        "Attribute": "Normal ↔ Carefree personality",
        "Offset": 341,
        "Data type": "Signed byte",
        "Lookup": None,
    },
    {
        "Attribute": "Favourite fruit",
        "Offset": 343,
        "Data type": "Byte",
        "Lookup": "FavouriteFruit",
    },
    {
        "Attribute": "Cough level",
        "Offset": 346,
        "Data type": "Signed byte",
        "Lookup": None,
    },
    {
        "Attribute": "Cold level",
        "Offset": 347,
        "Data type": "Signed byte",
        "Lookup": None,
    },
    {
        "Attribute": "Rash level",
        "Offset": 348,
        "Data type": "Signed byte",
        "Lookup": None,
    },
    {
        "Attribute": "Runny nose level",
        "Offset": 349,
        "Data type": "Signed byte",
        "Lookup": None,
    },
    {
        "Attribute": "Hiccups level",
        "Offset": 350,
        "Data type": "Signed byte",
        "Lookup": None,
    },
    {
        "Attribute": "Stomach ache level",
        "Offset": 351,
        "Data type": "Signed byte",
        "Lookup": None,
    },
    {
        "Attribute": "SA2B classroom skills",
        "Offset": 352,
        "Data type": "Int",
        "Lookup": "ClassroomLessonFlags",
    },
    {
        "Attribute": "SA2B toys",
        "Offset": 356,
        "Data type": "Short",
        "Lookup": "ToyFlags",
    },
    {
        "Attribute": "SA2B Sonic bond",
        "Offset": 364,
        "Data type": "Signed byte",
        "Lookup": None,
    },
    {
        "Attribute": "SA2B Shadow bond",
        "Offset": 370,
        "Data type": "Signed byte",
        "Lookup": None,
    },
    {
        "Attribute": "SA2B Tails bond",
        "Offset": 376,
        "Data type": "Signed byte",
        "Lookup": None,
    },
    {
        "Attribute": "SA2B Eggman bond",
        "Offset": 382,
        "Data type": "Signed byte",
        "Lookup": None,
    },
    {
        "Attribute": "SA2B Knuckles bond",
        "Offset": 388,
        "Data type": "Signed byte",
        "Lookup": None,
    },
    {
        "Attribute": "SA2B Rouge bond",
        "Offset": 394,
        "Data type": "Signed byte",
        "Lookup": None,
    },
    {
        "Attribute": "Reset trigger",
        "Offset": 1080,
        "Data type": "Boolean",
        "Lookup": None,
    },
    {
        "Attribute": "Swim stat grade 1",
        "Offset": 1172,
        "Data type": "Byte",
        "Lookup": "Grade",
    },
    {
        "Attribute": "Swim stat grade 2",
        "Offset": 1173,
        "Data type": "Byte",
        "Lookup": "Grade",
    },
    {
        "Attribute": "Fly stat grade 1",
        "Offset": 1174,
        "Data type": "Byte",
        "Lookup": "Grade",
    },
    {
        "Attribute": "Fly stat grade 2",
        "Offset": 1175,
        "Data type": "Byte",
        "Lookup": "Grade",
    },
    {
        "Attribute": "Run stat grade 1",
        "Offset": 1176,
        "Data type": "Byte",
        "Lookup": "Grade",
    },
    {
        "Attribute": "Run stat grade 2",
        "Offset": 1177,
        "Data type": "Byte",
        "Lookup": "Grade",
    },
    {
        "Attribute": "Power stat grade 1",
        "Offset": 1178,
        "Data type": "Byte",
        "Lookup": "Grade",
    },
    {
        "Attribute": "Power stat grade 2",
        "Offset": 1179,
        "Data type": "Byte",
        "Lookup": "Grade",
    },
    {
        "Attribute": "Stamina stat grade 1",
        "Offset": 1180,
        "Data type": "Byte",
        "Lookup": "Grade",
    },
    {
        "Attribute": "Stamina stat grade 2",
        "Offset": 1181,
        "Data type": "Byte",
        "Lookup": "Grade",
    },
    {
        "Attribute": "Luck stat grade 1",
        "Offset": 1182,
        "Data type": "Byte",
        "Lookup": None,
    },
    {
        "Attribute": "Luck stat grade 2",
        "Offset": 1183,
        "Data type": "Byte",
        "Lookup": None,
    },
    {
        "Attribute": "Intelligence stat grade 1",
        "Offset": 1184,
        "Data type": "Byte",
        "Lookup": None,
    },
    {
        "Attribute": "Intelligence stat grade 2",
        "Offset": 1185,
        "Data type": "Byte",
        "Lookup": None,
    },
    {
        "Attribute": "Unknown stat grade 1",
        "Offset": 1186,
        "Data type": "Byte",
        "Lookup": None,
    },
    {
        "Attribute": "Unknown stat grade 2",
        "Offset": 1187,
        "Data type": "Byte",
        "Lookup": None,
    },
    {
        "Attribute": "Favourite fruit 1",
        "Offset": 1222,
        "Data type": "Byte",
        "Lookup": "FavouriteFruit",
    },
    {
        "Attribute": "Favourite fruit 2",
        "Offset": 1223,
        "Data type": "Byte",
        "Lookup": "FavouriteFruit",
    },
    {
        "Attribute": "Colour 1",
        "Offset": 1228,
        "Data type": "Byte",
        "Lookup": "SA2BColour",
    },
    {
        "Attribute": "Colour 2",
        "Offset": 1229,
        "Data type": "Byte",
        "Lookup": "SA2BColour",
    },
    {
        "Attribute": "Mono-tone flag 1",
        "Offset": 1230,
        "Data type": "Boolean",
        "Lookup": None,
    },
    {
        "Attribute": "Mono-tone flag 2",
        "Offset": 1231,
        "Data type": "Boolean",
        "Lookup": None,
    },
    {
        "Attribute": "Texture 1",
        "Offset": 1232,
        "Data type": "Byte",
        "Lookup": "SA2BTexture",
    },
    {
        "Attribute": "Texture 2",
        "Offset": 1233,
        "Data type": "Byte",
        "Lookup": "SA2BTexture",
    },
    {
        "Attribute": "Shiny flag 1",
        "Offset": 1234,
        "Data type": "Boolean",
        "Lookup": None,
    },
    {
        "Attribute": "Shiny flag 2",
        "Offset": 1235,
        "Data type": "Boolean",
        "Lookup": None,
    },
    {
        "Attribute": "Egg colour 1",
        "Offset": 1236,
        "Data type": "Byte",
        "Lookup": "SA2BEggColour",
    },
    {
        "Attribute": "Egg colour 2",
        "Offset": 1237,
        "Data type": "Byte",
        "Lookup": "SA2BEggColour",
    },
]
