"""
Data and lookups for chao save files.
"""
from typing import Dict, List, Union


SAVE_FILE_OFFSETS: List[Dict[str, Union[str, int, None]]] = [
    {
        "Attribute": "UNKNOWN - Garden Entries?",
        "Group": "Unknown",
        "Offset": 12380,
        "Data type": "Byte",
        "Lookup": None,
    },
    {
        "Attribute": "UNKNOWN 1 - int?",
        "Group": "Unknown",
        "Offset": 12499,
        "Data type": "Int",
        "Lookup": None,
    },
    {
        "Attribute": "UNKNOWN 2 - int?",
        "Group": "Unknown",
        "Offset": 12507,
        "Data type": "Int",
        "Lookup": None,
    },
    {
        "Attribute": "Challenge Races Won",
        "Group": "Races",
        "Offset": 14301,
        "Data type": "Byte",
        "Lookup": None,
    },
    {
        "Attribute": "Hero Races Won",
        "Group": "Races",
        "Offset": 14302,
        "Data type": "Byte",
        "Lookup": None,
    },
    {
        "Attribute": "Dark Races Won",
        "Group": "Races",
        "Offset": 14303,
        "Data type": "Byte",
        "Lookup": None,
    },
    {
        "Attribute": "Crab Pool Record Time",
        "Group": "Races",
        "Offset": 14315,
        "Data type": "Time",
        "Lookup": None,
    },
    {
        "Attribute": "Crab Pool Record Holder",
        "Group": "Races",
        "Offset": 14346,
        "Data type": "Name",
        "Lookup": None,
    },
    {
        "Attribute": "Stumo Valley Record Time",
        "Group": "Races",
        "Offset": 14366,
        "Data type": "Time",
        "Lookup": None,
    },
    {
        "Attribute": "Stumo Valley Record Holder",
        "Group": "Races",
        "Offset": 14397,
        "Data type": "Name",
        "Lookup": None,
    },
    {
        "Attribute": "Mushroom Forest Record Time",
        "Group": "Races",
        "Offset": 14417,
        "Data type": "Time",
        "Lookup": None,
    },
    {
        "Attribute": "Mushroom Forest Record Holder",
        "Group": "Races",
        "Offset": 14448,
        "Data type": "Name",
        "Lookup": None,
    },
    {
        "Attribute": "Block Canyon Record Time",
        "Group": "Races",
        "Offset": 14473,
        "Data type": "Time",
        "Lookup": None,
    },
    {
        "Attribute": "Block Canyon Record Holder",
        "Group": "Races",
        "Offset": 14504,
        "Data type": "Name",
        "Lookup": None,
    },
    {
        "Attribute": "Aquamarine Record Time",
        "Group": "Races",
        "Offset": 14529,
        "Data type": "Time",
        "Lookup": None,
    },
    {
        "Attribute": "Aquamarine Record Holder",
        "Group": "Races",
        "Offset": 14560,
        "Data type": "Name",
        "Lookup": None,
    },
    {
        "Attribute": "Topaz Record Time",
        "Group": "Races",
        "Offset": 14585,
        "Data type": "Time",
        "Lookup": None,
    },
    {
        "Attribute": "Topaz Record Holder",
        "Group": "Races",
        "Offset": 14616,
        "Data type": "Name",
        "Lookup": None,
    },
    {
        "Attribute": "Peridot Record Time",
        "Group": "Races",
        "Offset": 14641,
        "Data type": "Time",
        "Lookup": None,
    },
    {
        "Attribute": "Peridot Record Holder",
        "Group": "Races",
        "Offset": 14672,
        "Data type": "Name",
        "Lookup": None,
    },
    {
        "Attribute": "Garnet Record Time",
        "Group": "Races",
        "Offset": 14697,
        "Data type": "Time",
        "Lookup": None,
    },
    {
        "Attribute": "Garnet Record Holder",
        "Group": "Races",
        "Offset": 14728,
        "Data type": "Name",
        "Lookup": None,
    },
    {
        "Attribute": "Onyx Record Time",
        "Group": "Races",
        "Offset": 14753,
        "Data type": "Time",
        "Lookup": None,
    },
    {
        "Attribute": "Onyx Record Holder",
        "Group": "Races",
        "Offset": 14784,
        "Data type": "Name",
        "Lookup": None,
    },
    {
        "Attribute": "Diamond Record Time",
        "Group": "Races",
        "Offset": 14809,
        "Data type": "Time",
        "Lookup": None,
    },
    {
        "Attribute": "Diamond Record Holder",
        "Group": "Races",
        "Offset": 14840,
        "Data type": "Name",
        "Lookup": None,
    },
]
